### ISSUE TITLE
Debug messages always on

### ISSUE THREAD

**Issue by rpm91** [d2r2/go-i2c#2]
At first i didn´t noticed because i wanted it and set
i2c.Debug = true
but now i want to deactivate it but the debugmessages are always on even if i set
i2c.Debug false

Can you please tell me if it is a bug or if i missing something.
Thank you

**Comment by marccay** [comment]
Was missing the actual check before each debug was printed. Added a pull request adding that bool check before every debug print that will fix your issue.

You can just add if v.Debug == true { } before every lg.Debugf()

**Comment by d2r2** [comment]
Hi @rpm91! Sorry for late response. In fact field i2c.Debug has been abandoned and will be removed from code, because this variable have no effect to the current log output logic.

In order to manage verbosity output of d2r2/go-i2c package you should insert in your main() function call
```
	// Uncomment/comment next lines to suppress/increase verbosity of output
	logger.ChangePackageLogLevel("i2c", logger.InfoLevel)
```
, because in this case verbosity of package will be switched from `logger.DebugLevel` to `logger.InfoLevel`.
